package gec.scf.file.configuration;

public enum ValidationType {
	EQUAL_TO_UPLOAD_DATE, EQUAL_OR_GREATER_THAN_UPLOAD_DATE, GREATER_THAN_UPLOAD_DATE, EQUAL_OR_LESS_THAN_UPLOAD_DATE, LESS_THAN_UPLOAD_DATE, EQUAL_TO_HEADER_FIELD
}
